os:
  - linux
language: node_js
node_js:
  - '8.3'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
branches:
  only:
  - master
before_install:
  - cd frontend
  - npm install -g @angular/cli@7.0.6
script:
  - ng test -no-progress --browsers=ChromeHeadlessNoSandbox 
  - ng e2e
  - ng build
