os:
  - linux
language: node_js
node_js:
  - '8.3'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
branches:
  only:
  - master
before_install:
  - cd frontend
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@7.1.4
  - ng --version
install:
  - npm ci
script:
  - ng test -no-progress --browsers=ChromeHeadlessNoSandbox 
  - ng e2e
  - ng build
