os:
  - linux
language: node_js
node_js:
  - '8.3'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
branches:
  only:
  - master
before_install:
  - cd frontend
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm install -g @angular/cli@7.1.4
script:
  - ng build
